### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by albertoceballos** [Borda/kaggle_plant-pathology#10]
Is the plant pathology 2021 dataset used in the Pytorch Lightning notebook a resized version of the dataset? There are some commands that are commented out:

``# ! apt-get install -qq -y imagemagick``
``# ! mogrify -resize 960 train_images/*.jpg``

Were these commands used to resize the dataset before running the notebook?

**Comment by edgarriba** [comment]
Yes, we generated a downscaled version of the dataset offline due to a bottleneck issue with loading large images with pil.

**Comment by Borda** [comment]
yes, you can also download it here from Kaggle - https://www.kaggle.com/jirkaborovec/plant-pathology-2021-fgvc8-960px
