### ISSUE TITLE
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms'

### ISSUE THREAD

**Issue by atamazian** [Borda/kaggle_plant-pathology#8]
## 🐛 Bug

ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms' when trying to import `PlantPathologyDM`

### To Reproduce

1. Import  `PlantPathologyDM`
2. See error

### Expected behavior
`InterpolationMode` should be imported correctly

### Additional context
Tested on torchvision==0.8.1.

**Comment by tomasvdb** [comment]
I solved the same problem by upgrading to torchvison 0.9.1

**Comment by atamazian** [comment]
I found an easy fix which will make the package compliant with torchvision=0.8.1. Just remove `InterpolationMode` import and code related to it. `torchvision.transforms.Resize` uses `bilinear` interpolation by default, so there's no need to specify it directly.
